//Auth Actions
export const GET_ERRORS = "GET_ERRORS";
export const USER_LOADING = "USER_LOADING";
export const SET_CURRENT_USER = "SET_CURRENT_USER";
export const SET_CURRENT_ADMIN = "SET_CURRENT_ADMIN";

//Design Actions
export const SET_DESIGN_COLOR = "SET_DESIGN_COLOR";
export const SET_DESIGN_FONT = "SET_DESIGN_FONT";
export const TOGGLE_MODAL = "TOGGLE_MODAL";
export const SET_FONT_SIZE = "SET_FONT_SIZE";
export const SET_FONT_ROTATION = "SET_FONT_ROTATION";
export const SET_FONT_WEIGHT = "SET_FONT_WEIGHT";
export const SET_LINE_HEIGHT = "SET_LINE_HEIGHT";
export const SET_TEXT_COLOR = "SET_TEXT_COLOR";
export const SAVE_LOGO = "SAVE_LOGO";
export const SET_LOGO_SIZE = "SET_LOGO_SIZE";
export const SET_LOGO_ROTATION = "SET_LOGO_ROTATION";
export const SAVE_DATA = "SAVE_DATA";

//DrawingActions
export const SET_PRIMARY_SOCK_COLOR = "SET_PRIMARY_SOCK_COLOR";
export const SET_SECONDARY_SOCK_COLOR = "SET_SECONDARY_SOCK_COLOR";

//Bottom Sock Actions
export const ADD_SHAPE = "ADD_SHAPE";
export const UPDATE_SHAPES = "UPDATE_SHAPES";
export const SET_SHAPE_COLOR = "SET_SHAPE_COLOR";
export const ADD_BOTTOM_TEXT = "ADD_BOTTOM_TEXT";
export const UPDATE_BOTTOM_TEXT = "UPDATE_BOTTOM_TEXT";
export const SELECT_BOTTOM_TEXT = "SELECT_BOTTOM_TEXT";
export const ADD_BOTTOM_IMAGE = "SAVE_BOTTOM_IMAGE";
export const UPDATE_BOTTOM_IMAGES = "UPDATE_BOTTOM_IMAGES";
export const SELECT_BOTTOM_IMAGE = "SELECT_BOTTOM_IMAGE";
export const COPY_BOTTOM_IMAGE = "COPY_BOTTOM_IMAGE";
export const DELETE_BOTTOM_IMAGE = "DELETE_BOTTOM_IMAGE";

//Side Sock Actions
export const ADD_SIDE_TEXT = "ADD_SIDE_TEXT";
export const UPDATE_SIDE_TEXT = "UPDATE_SIDE_TEXT";
export const SELECT_SIDE_TEXT = "SELECT_SIDE_TEXT";
export const ADD_SIDE_IMAGE = "ADD_SIDE_IMAGE";
export const UPDATE_SIDE_IMAGES = "UPDATE_SIDE_IMAGES";
export const SELECT_SIDE_IMAGE = "SELECT_SIDE_IMAGE";
export const COPY_SIDE_IMAGE = "COPY_SIDE_IMAGE";
export const DELETE_SIDE_IMAGE = "DELETE_SIDE_IMAGE";
export const GET_SELECTED_TEXT_DETAILS = "GET_SELECTED_TEXT_DETAILS";

//Top Sock Actions
export const ADD_TOP_TEXT = "ADD_TOP_TEXT";
export const UPDATE_TOP_TEXT = "UPDATE_TOP_TEXT";
export const SELECT_TOP_TEXT = "SELECT_TOP_TEXT";
export const ADD_TOP_IMAGE = "ADD_TOP_IMAGE";
export const UPDATE_TOP_IMAGES = "UPDATE_TOP_IMAGES";
export const SELECT_TOP_IMAGE = "SELECT_TOP_IMAGE";
export const COPY_TOP_IMAGE = "COPY_TOP_IMAGE";
export const DELETE_TOP_IMAGE = "DELETE_TOP_IMAGE";

//Grid Actions
export const SET_GRID_SIZE = "SET_GRID_SIZE";

//Admin Actions
export const GET_ALL_USERS = "GET_ALL_USERS";
